MODEL_NAME : "movenet_thunder"
#@param ["movenet_lightning", "movenet_thunder", "movenet_lightning_f16.tflite", "movenet_thunder_f16.tflite", "movenet_lightning_int8.tflite", "movenet_thunder_int8.tflite"]

KEYPOINT_THRESH_SCORE_CROP : 0.2    # 0.2 initial
KEYPOINT_THRESH_SCORE_DRAW : 0.11   # 0.11 initial

EDGE_VEL_THRESH : 10

XY_NAMES : ["start_x","start_y", "end_x", "end_y"]