? !!python/tuple
- 0
- 1
: m
? !!python/tuple
- 0
- 2
: c
? !!python/tuple
- 0
- 5
: m
? !!python/tuple
- 0
- 6
: c
? !!python/tuple
- 1
- 3
: m
? !!python/tuple
- 2
- 4
: c
? !!python/tuple
- 5
- 6
: y
? !!python/tuple
- 5
- 7
: m
? !!python/tuple
- 5
- 11
: m
? !!python/tuple
- 6
- 8
: c
? !!python/tuple
- 6
- 12
: c
? !!python/tuple
- 7
- 9
: m
? !!python/tuple
- 8
- 10
: c
? !!python/tuple
- 11
- 12
: y
? !!python/tuple
- 11
- 13
: m
? !!python/tuple
- 12
- 14
: c
? !!python/tuple
- 13
- 15
: m
? !!python/tuple
- 14
- 16
: c
